import os
import datetime

def save_to_obsidian(agenda: str, reports: dict, final_decision: str):
    """
    会議の結果を Obsidian Vault 形式の Markdown として保存する。
    """
    # Vaultのパス設定（MAINTENANCE_LOG.json の設定に合わせる）
    VAULT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../obsidian_vault/meetings")
    os.makedirs(VAULT_PATH, exist_ok=True)

    now = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M:%S")
    filename = f"{now.strftime('%Y%m%d_%H%M%S')}_{agenda[:20]}.md"
    file_path = os.path.join(VAULT_PATH, filename)

    # Frontmatterの作成
    content = f"""---
title: "{agenda}"
date: {date_str}
time: {time_str}
type: meeting_minutes
tags: [boardmeeting, decision, ai_corp]
---

# 🏢 会議議事録: {agenda}

## 📅 開催情報
- **日時**: {date_str} {time_str}
- **場所**: AI株式会社 バーチャルボードルーム

## 👑 CEO最終決断
> [!IMPORTANT]
> {final_decision}

---

## 👥 各役員の報告・分析

"""
    # 各役員の報告を追加
    for role, report in reports.items():
        content += f"### 👤 {role}\n{report}\n\n"

    content += "\n--- \n*Generated by AI Corporation OS Archivist*"

    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  [🗂️ Obsidian Archivist] 議事録を保存しました: {filename}")
        return file_path
    except Exception as e:
        print(f"  [❌ Obsidian Archivist Error] 保存失敗: {e}")
        return None
